version: "3.1"

services:
  core:
    build: .
        
    expose:
      - 9017
    ports:
      - 9017:9017/tcp
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      PASSWORD_DB_JWT: "Apolo.9217"

 