server:
  port: 9018
app1:
  exchange:
    name: app1-exchange
  queue:
    name: app1-queue
  routing:
    key: app1-routing-key
app2:
  queue:
    name: app2-queue
  routing:
    key: app2-routing-key
logging:
  level:
    org:
      hibernate:
        SQL: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    password: Apolo.9217
    url: jdbc:mysql://localhost:3306/demo
    username: root
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        retry:
          initial-interval: 5000
    password: guest
    port: 5672
    username: guest
